# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new internal build to Google Play"
  lane :internal do
    gradle(task: "clean assembleRelease")
    upload_to_play_store(
      track: 'internal'
    )
  end

  desc "Promote an internal build to beta"
  lane :promote_internal_to_beta do
    supply(
      package_name: "com.blaxsoftware.directcallwidget",
      track: "internal",
      track_promote_to: "beta",
      skip_upload_apk: true,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  desc "Submit a new Beta Build to Google Play"
  lane :beta do
    gradle(task: "clean assembleRelease")
    upload_to_play_store(
      track: 'beta'
    )
    # crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
