name: PR checks

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: build
        run: ./gradlew build

      - name: publish unit tests results
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: '**/build/reports/tests'
